name: docusaurus cicd
run-name: ${{ github.actor }} is trying actions to make docusaurus
on:
  push:
    branches: 
      - main
  pull_request:
    branches:
      - main

jobs:
  build-job:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v5
      - name: Initialize Node.JS for this job
        uses: actions/setup-node@v6
        with:
          node-version: '20.x'
      - run: npm version
      - run: npm run build

